apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-user: {{ .Values.mysql.user | b64enc }}
  mysql-password: {{ .Values.mysql.password | b64enc }}
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc }}
  mysql-database: {{ .Values.mysql.database | b64enc }}

