replicaCount: 2

image:
  repository: beekman9527/cpumemload
  tag: latest
  pullPolicy: IfNotPresent

resources:
  container1:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  container2:
    limits:
      cpu: 700m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  container3:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 128Mi
